directories:
  output: release
  buildResources: build
appId: com.hubstore.app
productName: HubStore
files:
  - filter:
      - dist/**/*
      - node_modules/.prisma/**/*
      - node_modules/@prisma/**/*
      - prisma/**/*
      - package.json
extraResources:
  - from: prisma/dev.db
    to: dev.db
win:
  target: nsis
  artifactName: HubStore-Setup-${version}.exe
npmRebuild: false
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
electronVersion: 41.4.0
